name: Supabase Auto Ping

on:
  schedule:
    - cron: "0 */6 * * *"  # Setiap 6 jam
  workflow_dispatch:       # Bisa dijalankan manual juga

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Projects
        run: |
          curl --max-time 10 -I https://plrfinzrxysakgrsjcvg.supabase.co
          curl --max-time 10 -I https://ytacwxsvfdqtvjbbjjnl.supabase.co
